using System;
using System.IO;
using System.Linq;

using Kiota.Builder.CodeDOM;
using Kiota.Builder.Writers;

using Xunit;

namespace Kiota.Builder.Tests.Writers.AL;

public sealed class CodeEnumWriterTests : IDisposable
{
    private const string AutoGenerationHeader = "// <auto-generated/>";
    private const string DefaultPath = "./";
    private const string DefaultName = "name";
    private readonly StringWriter tw;
    private readonly LanguageWriter writer;
    private readonly CodeEnum currentEnum;
    private const string EnumName = "someEnum";

    public CodeEnumWriterTests()
    {
        writer = LanguageWriter.GetLanguageWriter(GenerationLanguage.AL, DefaultPath, DefaultName);
        tw = new StringWriter();
        writer.SetTextWriter(tw);
        var root = CodeNamespace.InitRootNamespace();
        currentEnum = root.AddEnum(new CodeEnum
        {
            Name = EnumName,
        }).First();
    }

    public void Dispose()
    {
        tw?.Dispose();
        GC.SuppressFinalize(this);
    }

    [Fact]
    public void WritesAutoGeneratedHeader()
    {
        currentEnum.AddOption(new CodeEnumOption { Name = "Option1" });
        writer.Write(currentEnum);
        var result = tw.ToString();
        Assert.Contains(AutoGenerationHeader, result);
    }

    [Fact]
    public void WritesEnumDeclarationWithDefaultObjectId()
    {
        currentEnum.AddOption(new CodeEnumOption { Name = "Option1" });
        writer.Write(currentEnum);
        var result = tw.ToString();
        // No object-id CustomData -> writer falls back to "0"
        Assert.Contains($"enum 0 \"{EnumName}\"", result);
    }

    [Fact]
    public void WritesEnumDeclarationWithObjectId()
    {
        currentEnum.CustomData["object-id"] = "50123";
        currentEnum.AddOption(new CodeEnumOption { Name = "Option1" });
        writer.Write(currentEnum);
        var result = tw.ToString();
        Assert.Contains($"enum 50123 \"{EnumName}\"", result);
    }

    [Fact]
    public void WritesValueOptionWithIndexAndCaption()
    {
        currentEnum.AddOption(new CodeEnumOption { Name = "Option1" });
        writer.Write(currentEnum);
        var result = tw.ToString();
        Assert.Contains("value(0; \"Option1\")", result);
        Assert.Contains("Caption = 'Option1', Locked = true;", result);
    }

    [Fact]
    public void WritesMultipleValueOptionsWithIncrementingIndex()
    {
        currentEnum.AddOption(new CodeEnumOption { Name = "First" });
        currentEnum.AddOption(new CodeEnumOption { Name = "Second" });
        writer.Write(currentEnum);
        var result = tw.ToString();
        Assert.Contains("value(0; \"First\")", result);
        Assert.Contains("value(1; \"Second\")", result);
    }

    [Fact]
    public void WritesObjectPropertyOptionsBeforeValues()
    {
        var extensible = new CodeEnumOption { Name = "Extensible" };
        extensible.CustomData["object-property"] = "true";
        extensible.CustomData["value"] = "true";
        currentEnum.AddOption(extensible);
        currentEnum.AddOption(new CodeEnumOption { Name = "Option1" });
        writer.Write(currentEnum);
        var result = tw.ToString();
        Assert.Contains("Extensible = true;", result);
        // The object-property option must not be emitted as an enum value
        Assert.DoesNotContain("value(0; \"Extensible\")", result);
    }

    [Fact]
    public void WritesNamespaceWhenParentNamespaceIsNamed()
    {
        var root = CodeNamespace.InitRootNamespace();
        var ns = root.AddNamespace("Vendor.Api.Models");
        var scopedEnum = ns.AddEnum(new CodeEnum { Name = "ScopedEnum" }).First();
        scopedEnum.AddOption(new CodeEnumOption { Name = "Option1" });
        writer.Write(scopedEnum);
        var result = tw.ToString();
        Assert.Contains("namespace Vendor.Api.Models;", result);
    }

    [Fact]
    public void EscapesSingleQuoteInCaptionWireName()
    {
        currentEnum.AddOption(new CodeEnumOption { Name = "Option1", SerializationName = "O'Reilly" });
        writer.Write(currentEnum);
        var result = tw.ToString();
        // The wire name flows into a single-quoted AL Caption literal and must be escaped by doubling.
        Assert.Contains("Caption = 'O''Reilly', Locked = true;", result);
        Assert.DoesNotContain("Caption = 'O'Reilly'", result);
    }
}
