using System;
using System.IO;
using System.Linq;

using Kiota.Builder.CodeDOM;
using Kiota.Builder.Writers;

using Xunit;

namespace Kiota.Builder.Tests.Writers.AL;

public sealed class CodeClassDeclarationWriterTests : IDisposable
{
    private const string AutoGenerationHeader = "// <auto-generated/>";
    private const string DefaultPath = "./";
    private const string DefaultName = "name";
    private readonly StringWriter tw;
    private readonly LanguageWriter writer;
    private readonly CodeClass parentClass;
    private const string ClassName = "SomeClient";

    public CodeClassDeclarationWriterTests()
    {
        writer = LanguageWriter.GetLanguageWriter(GenerationLanguage.AL, DefaultPath, DefaultName);
        tw = new StringWriter();
        writer.SetTextWriter(tw);
        var root = CodeNamespace.InitRootNamespace();
        var ns = root.AddNamespace("Vendor.Api");
        parentClass = ns.AddClass(new CodeClass
        {
            Name = ClassName,
            Kind = CodeClassKind.Custom,
        }).First();
    }

    public void Dispose()
    {
        tw?.Dispose();
        GC.SuppressFinalize(this);
    }

    [Fact]
    public void WritesAutoGeneratedHeader()
    {
        writer.Write(parentClass.StartBlock);
        var result = tw.ToString();
        Assert.Contains(AutoGenerationHeader, result);
    }

    [Fact]
    public void WritesNamespace()
    {
        writer.Write(parentClass.StartBlock);
        var result = tw.ToString();
        Assert.Contains("namespace Vendor.Api;", result);
    }

    [Fact]
    public void WritesCodeunitDeclarationWithDefaultObjectId()
    {
        writer.Write(parentClass.StartBlock);
        var result = tw.ToString();
        Assert.Contains($"codeunit 0 \"{ClassName}\"", result);
    }

    [Fact]
    public void WritesCodeunitDeclarationWithObjectId()
    {
        parentClass.CustomData["object-id"] = "50200";
        writer.Write(parentClass.StartBlock);
        var result = tw.ToString();
        Assert.Contains($"codeunit 50200 \"{ClassName}\"", result);
    }

    [Fact]
    public void DoesNotWriteNamespacePrefixInObjectName()
    {
        parentClass.CustomData["object-id"] = "50200";
        writer.Write(parentClass.StartBlock);
        var result = tw.ToString();
        // AL object names must not contain dots; only the bare class name is quoted.
        Assert.DoesNotContain($"\"Vendor.Api.{ClassName}\"", result);
        Assert.Contains($"\"{ClassName}\"", result);
    }

    [Fact]
    public void SkipsNestedClass()
    {
        var root = CodeNamespace.InitRootNamespace();
        var ns = root.AddNamespace("Vendor.Api");
        var outer = ns.AddClass(new CodeClass { Name = "Outer", Kind = CodeClassKind.Custom }).First();
        var nested = outer.AddInnerClass(new CodeClass { Name = "Nested", Kind = CodeClassKind.Custom }).First();
        writer.Write(nested.StartBlock);
        var result = tw.ToString();
        // Nested classes are unsupported in AL; nothing should be emitted.
        Assert.Empty(result);
        Assert.True(nested.CustomData.ContainsKey("skip"));
    }
}
