using System;
using System.IO;
using System.Linq;

using Kiota.Builder.CodeDOM;
using Kiota.Builder.Writers;

using Xunit;

namespace Kiota.Builder.Tests.Writers.AL;

public sealed class CodeInterfaceDeclarationWriterTests : IDisposable
{
    private const string AutoGenerationHeader = "// <auto-generated/>";
    private const string DefaultPath = "./";
    private const string DefaultName = "name";
    private readonly StringWriter tw;
    private readonly LanguageWriter writer;
    private readonly CodeInterface parentInterface;

    public CodeInterfaceDeclarationWriterTests()
    {
        writer = LanguageWriter.GetLanguageWriter(GenerationLanguage.AL, DefaultPath, DefaultName);
        tw = new StringWriter();
        writer.SetTextWriter(tw);
        var root = CodeNamespace.InitRootNamespace();
        var ns = root.AddNamespace("Vendor.Api");
        parentInterface = ns.AddInterface(new CodeInterface
        {
            Name = "IMyThing",
            Kind = CodeInterfaceKind.Model,
            OriginalClass = new CodeClass { Name = "MyThing", Kind = CodeClassKind.Model },
        }).First();
    }

    public void Dispose()
    {
        tw?.Dispose();
        GC.SuppressFinalize(this);
    }

    [Fact]
    public void WritesAutoGeneratedHeaderAndNamespace()
    {
        writer.Write(parentInterface.StartBlock);
        var result = tw.ToString();
        Assert.Contains(AutoGenerationHeader, result);
        Assert.Contains("namespace Vendor.Api;", result);
    }

    [Fact]
    public void WritesInterfaceDeclaration()
    {
        writer.Write(parentInterface.StartBlock);
        var result = tw.ToString();
        Assert.Contains("interface \"IMyThing\"", result);
    }

    [Fact]
    public void WritesMethodSignatureWithoutBody()
    {
        parentInterface.AddMethod(new CodeMethod
        {
            Name = "DoThing",
            ReturnType = new CodeType { Name = "string" },
        });
        writer.Write(parentInterface.StartBlock);
        var result = tw.ToString();
        Assert.Contains("DoThing(): Text", result);
        Assert.DoesNotContain("begin", result);
    }
}
