using System;
using System.Linq;
using Kiota.Builder.CodeDOM;
using Kiota.Builder.Extensions;

namespace Kiota.Builder.Writers.AL;

public class CodeClassDeclarationWriter : BaseElementWriter<ClassDeclaration, ALConventionService>
{
    public static string AutoGenerationHeader => "// <auto-generated/>";

    public CodeClassDeclarationWriter(ALConventionService conventionService) : base(conventionService) { }

    public override void WriteCodeElement(ClassDeclaration codeElement, LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(codeElement);
        ArgumentNullException.ThrowIfNull(writer);

        if (codeElement.Parent is not CodeClass parentClass)
            return;
        if (parentClass.ParentIsSkipped()) // seems to be a nested class, we don't support that in AL
            return;
        if (parentClass.Parent is not CodeNamespace) // seems to be a nested class, we don't support that in AL
        {
            parentClass.SetFlag(ALCustomDataKeys.Skip);
            return;
        }

        // Auto-generation header
        writer.WriteLine(AutoGenerationHeader);

        // Namespace
        if (parentClass.Parent is CodeNamespace parentNs && !string.IsNullOrEmpty(parentNs.Name))
        {
            writer.WriteLine($"namespace {parentNs.Name};");
            writer.WriteLine();
        }

        // Usings
        WriteUsings(codeElement, writer);

        // Documentation
        WriteDocumentation(parentClass, writer);

        // Object ID
        var objectId = parentClass.GetData(ALCustomDataKeys.ObjectId, "0");

        // Class name (no namespace prefix - AL does not allow dots in object names)
        var className = parentClass.Name;

        // Implements
        var implements = codeElement.Implements.ToList();
        var implementsClause = implements.Count > 0
            ? $" implements {string.Join(", ", implements.Select(i => $"\"{i.Name}\""))}"
            : string.Empty;

        // Pragma disable for object declaration
        var pragmas = parentClass.GetData(ALCustomDataKeys.Pragmas);
        if (!string.IsNullOrEmpty(pragmas))
            writer.WriteLine($"#pragma warning disable {pragmas}", false);

        writer.WriteLine($"codeunit {objectId} \"{className}\"{implementsClause}");

        if (!string.IsNullOrEmpty(pragmas))
            writer.WriteLine($"#pragma warning restore {pragmas}", false);

        writer.StartBlock();

        // Object properties
        WriteObjectProperties(parentClass, writer);

        // Global variables
        WriteGlobalVariables(parentClass, writer);
    }

    private static void WriteUsings(ClassDeclaration codeElement, LanguageWriter writer)
    {
        var usings = codeElement.Usings
            .Select(u => u.IsExternal ? u.Declaration?.Name ?? u.Name : u.Name)
            .Where(u => !string.IsNullOrEmpty(u))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Order(StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (usings.Count == 0) return;

        foreach (var u in usings)
            writer.WriteLine($"using {u};");
        writer.WriteLine();
    }

    private static void WriteDocumentation(CodeClass parentClass, LanguageWriter writer)
    {
        if (parentClass.Documentation?.DescriptionAvailable == true)
        {
            var description = parentClass.Documentation.GetDescription(static t => t.Name);
            var pragmas = parentClass.GetData(ALCustomDataKeys.DocumentationPragmas);
            if (!string.IsNullOrEmpty(pragmas))
                writer.WriteLine($"#pragma warning disable {pragmas}", false);
            // Strip any CustomData metadata from description
            if (!string.IsNullOrEmpty(description))
            {
                writer.WriteLine("/// <summary>");
                writer.WriteLine($"/// {description}");
                writer.WriteLine("/// </summary>");
            }
            if (!string.IsNullOrEmpty(pragmas))
                writer.WriteLine($"#pragma warning restore {pragmas}", false);
        }
    }

    private static void WriteObjectProperties(CodeClass parentClass, LanguageWriter writer)
    {
        var objectProps = parentClass.Properties
            .Where(p => p.HasData(ALCustomDataKeys.ObjectProperty))
            .ToList();

        if (objectProps.Count == 0) return;

        foreach (var prop in objectProps)
        {
            var propName = prop.Name;
            var propValue = prop.GetData(ALCustomDataKeys.Value, string.Empty);
            if (string.IsNullOrEmpty(propValue))
                continue; // Skip properties without a value
            writer.WriteLine($"{propName} = {propValue};");
        }
        writer.WriteLine();
    }

    private void WriteGlobalVariables(CodeClass parentClass, LanguageWriter writer)
    {
        var globals = parentClass.Properties
            .Where(p => p.HasData(ALCustomDataKeys.GlobalVariable))
            .ToList();

        if (globals.Count == 0) return;

        // Convert to ALVariable instances
        var variables = globals.Select(p =>
        {
            var pragmas = p.GetData(ALCustomDataKeys.Pragmas);
            var value = p.GetData(ALCustomDataKeys.Value);
            var isLabel = p.Type.Name.Equals("Label", StringComparison.OrdinalIgnoreCase);
            var varValue = isLabel ? (value ?? string.Empty) : string.Empty;
            var isLockedLabel = p.GetFlag(ALCustomDataKeys.LockedLabel);

            return new ALVariable(p.Name, p.Type, varValue, string.Empty, pragmas ?? string.Empty, isLockedLabel);
        }).ToList();

        // Order: Codeunit types first, then others, alphabetically within groups
        var codeunitVars = variables
            .Where(v => v.Type?.Name?.StartsWith("Codeunit", StringComparison.OrdinalIgnoreCase) == true)
            .OrderBy(v => v.Type?.Name ?? string.Empty, StringComparer.OrdinalIgnoreCase)
            .ToList();
        var otherVars = variables
            .Where(v => v.Type?.Name?.StartsWith("Codeunit", StringComparison.OrdinalIgnoreCase) != true)
            .OrderBy(v => v.Type?.Name ?? string.Empty, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var ordered = codeunitVars.Concat(otherVars).ToList();

        writer.WriteLine("var");
        writer.IncreaseIndent();

        // Pragma disable for variables
        var varPragmas = parentClass.GetData(ALCustomDataKeys.PragmasVariables);
        if (!string.IsNullOrEmpty(varPragmas))
            writer.WriteLine($"#pragma warning disable {varPragmas}", false);

        foreach (var v in ordered)
            v.Write(writer, conventions);

        if (!string.IsNullOrEmpty(varPragmas))
            writer.WriteLine($"#pragma warning restore {varPragmas}", false);

        writer.DecreaseIndent();
        writer.WriteLine();
    }

}
