using System;
using System.Linq;
using Kiota.Builder.CodeDOM;
using Kiota.Builder.Extensions;

namespace Kiota.Builder.Writers.AL;

public class CodeClassDeclarationWriter : BaseElementWriter<ClassDeclaration, ALConventionService>
{
    // TODO-SF: add "Implements" to ClassDeclaration-objects in ALRefiner
    public static string AutoGenerationHeader => "// <auto-generated/>";
    public CodeClassDeclarationWriter(ALConventionService conventionService) : base(conventionService) { }
    public override void WriteCodeElement(ClassDeclaration codeElement, LanguageWriter writer)
    {
        var alWriter = writer as ALWriter;
        ArgumentNullException.ThrowIfNull(codeElement);
        ArgumentNullException.ThrowIfNull(alWriter);
        if (codeElement.ParentIsSkipped()) return;
        if (codeElement.Parent is not CodeClass parentClass) throw new InvalidOperationException($"The provided code element {codeElement.Name} doesn't have a parent of type {nameof(CodeClass)}");
        
        // Check if this is a parameter codeunit and handle it specially
        if (parentClass.GetCustomProperty("parameter-codeunit") == "true")
        {
            WriteParameterCodeunit(codeElement, alWriter, parentClass);
            return;
        }
        
        if (parentClass.Parent is not CodeNamespace)
        {
            // seems to be a nested class, we don't support that in AL
            ((IDocumentedElement)codeElement.Parent).AddCustomProperty("skip", "true");
            return;
        }
        if (codeElement.Parent?.Parent is CodeNamespace)
        {
            alWriter.WriteLine(AutoGenerationHeader);
            alWriter.WriteLine($"namespace {codeElement.Parent.Parent.Name};");
            alWriter.WriteLine();
            codeElement.Usings
                    .Where(x => (x.Declaration?.IsExternal ?? true) || !x.Declaration.Name.Equals(codeElement.Name, StringComparison.OrdinalIgnoreCase)) // needed for circular requests patterns like message folder
                    .Select(static x => x.Declaration?.IsExternal ?? false ?
                                    $"using {x.Declaration.Name.NormalizeNameSpaceName(".")};":
                                    $"using {x.Name.NormalizeNameSpaceName(".")};")
                    .Distinct(StringComparer.Ordinal)
                    .OrderBy(static x => x, StringComparer.Ordinal)
                    .ToList()
                    .ForEach(x => alWriter.WriteLine(x));
            alWriter.WriteLine();
        }
        var derivedTypes = (codeElement.Inherits is null ? Enumerable.Empty<string?>() : new string?[] { conventions.GetTypeString(codeElement.Inherits, parentClass) })
                                        .Union(codeElement.Implements.Select(static x => $"\"{x.Name}\""))
                                        .OfType<string>()
                                        .ToArray();
        var derivation = derivedTypes.Length != 0 ? "implements " + derivedTypes.Aggregate(static (x, y) => $"{x}, {y}") : string.Empty;
        var customProperties = parentClass.GetCustomProperties(); // save custom properties
        parentClass.RemoveCustomProperties(); // remove custom properties
        bool hasDescription = conventions.WriteLongDescription(parentClass, alWriter);
        conventions.WriteDeprecationAttribute(parentClass, alWriter);
        parentClass.SetCustomProperties(customProperties); // restore custom properties
        alWriter.WritePragmaConditionalDisable(parentClass.GetPragmas());
        alWriter.WriteLine($"codeunit {parentClass.GetObjectId()} {codeElement.Name.ToFirstCharacterUpperCase()} {derivation}");
        alWriter.WritePragmaConditionalRestore(parentClass.GetPragmas());
        alWriter.StartBlock();
        alWriter.WriteObjectProperties(parentClass.ObjectProperties().ToObjectProperties());
        alWriter.WriteVariablesDeclaration(parentClass.OrderedGlobalVariables(), parentClass);
    }
    
    private void WriteParameterCodeunit(ClassDeclaration codeElement, ALWriter alWriter, CodeClass parentClass)
    {
        var parentNamespace = parentClass.GetImmediateParentOfType<CodeNamespace>();
        if (parentNamespace == null) return;

        // Write codeunit declaration for parameter codeunit
        alWriter.WriteLine(AutoGenerationHeader);
        alWriter.WriteLine($"namespace {parentNamespace.Name};");
        alWriter.WriteLine();

        // Write usings if any
        codeElement.Usings
            .Where(x => (x.Declaration?.IsExternal ?? true) || !x.Declaration.Name.Equals(codeElement.Name, StringComparison.OrdinalIgnoreCase))
            .Select(static x => x.Declaration?.IsExternal ?? false ?
                            $"using {x.Declaration.Name.NormalizeNameSpaceName(".")};":
                            $"using {x.Name.NormalizeNameSpaceName(".")};")
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static x => x, StringComparer.Ordinal)
            .ToList()
            .ForEach(x => alWriter.WriteLine(x));

        if (codeElement.Usings.Any())
            alWriter.WriteLine();

        // Apply AL name abbreviation for 30-character limit
        var codeunitName = codeElement.Name;
        if (codeunitName.Length > 30 && ALConventionService.CanAbbreviate(codeunitName))
        {
            codeunitName = ALConventionService.AbbreviateName(codeunitName);
        }

        // Write codeunit header using the new Object ID approach
        alWriter.WritePragmaConditionalDisable(parentClass.GetPragmas());
        alWriter.WriteLine($"codeunit {parentClass.GetObjectId()} \"{codeunitName}\"");
        alWriter.WritePragmaConditionalRestore(parentClass.GetPragmas());
        alWriter.StartBlock();

        ALParameterCodeunitHelper.WriteParameterVariables(parentClass, alWriter);
        ALParameterCodeunitHelper.WriteParameterMethods(parentClass, alWriter);

        // Note: Removed alWriter.CloseBlock() to match regular codeunit pattern
        // The codeunit closing is handled by the framework, not here
    }
    
    private void WriteParameterVariables(CodeClass codeElement, ALWriter writer)
    {
        ALParameterCodeunitHelper.WriteParameterVariables(codeElement, writer);
    }

    private void WriteParameterMethods(CodeClass codeElement, ALWriter writer)
    {
        ALParameterCodeunitHelper.WriteParameterMethods(codeElement, writer);
    }
}
