using System;
using System.Linq;
using Kiota.Builder.CodeDOM;

namespace Kiota.Builder.Writers.AL;

public class CodeInterfaceDeclarationWriter : BaseElementWriter<InterfaceDeclaration, ALConventionService>
{
    public static string AutoGenerationHeader => "// <auto-generated/>";

    public CodeInterfaceDeclarationWriter(ALConventionService conventionService) : base(conventionService) { }

    public override void WriteCodeElement(InterfaceDeclaration codeElement, LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(codeElement);
        ArgumentNullException.ThrowIfNull(writer);
        if (codeElement.ParentIsSkipped())
            return;

        if (codeElement.Parent is not CodeInterface parentInterface)
            return;

        // Auto-generation header
        writer.WriteLine(AutoGenerationHeader);

        // Namespace
        if (parentInterface.Parent is CodeNamespace parentNs && !string.IsNullOrEmpty(parentNs.Name))
        {
            writer.WriteLine($"namespace {parentNs.Name};");
            writer.WriteLine();
        }

        // Documentation
        if (parentInterface.Documentation?.DescriptionAvailable == true)
        {
            var description = parentInterface.Documentation.GetDescription(static t => t.Name);
            if (!string.IsNullOrEmpty(description))
            {
                writer.WriteLine("/// <summary>");
                writer.WriteLine($"/// {description}");
                writer.WriteLine("/// </summary>");
            }
        }

        writer.WriteLine($"interface \"{parentInterface.Name}\"");
        writer.StartBlock();

        // Write method signatures (no bodies)
        foreach (var method in parentInterface.Methods.OrderBy(m => m.Name, StringComparer.OrdinalIgnoreCase))
        {
            var returnType = conventions.GetTypeString(method.ReturnType, method);
            var returnClause = !string.IsNullOrEmpty(returnType) && !returnType.Equals("void", StringComparison.OrdinalIgnoreCase)
                ? $": {returnType}" : string.Empty;

            var parameters = method.Parameters
                .Where(p => !p.CustomData.ContainsKey("local-variable"))
                .Select(p =>
                {
                    var typeName = conventions.GetTypeString(p.Type, p);
                    var byRef = p.CustomData.TryGetValue("by-ref", out var refVal) &&
                                refVal.Equals("true", StringComparison.OrdinalIgnoreCase);
                    return byRef ? $"var {p.Name}: {typeName}" : $"{p.Name}: {typeName}";
                });

            var paramStr = string.Join("; ", parameters);
            writer.WriteLine($"procedure {method.Name}({paramStr}){returnClause};");
        }

        // The CloseBlock will be written by CodeBlockEndWriter
    }
}
