using System;
using System.Globalization;
using System.Linq;
using Kiota.Builder.CodeDOM;
using Kiota.Builder.Extensions;

namespace Kiota.Builder.Writers.AL;

public class CodeEnumWriter : BaseElementWriter<CodeEnum, ALConventionService>
{
    public static string AutoGenerationHeader => "// <auto-generated/>";

    public CodeEnumWriter(ALConventionService conventionService) : base(conventionService) { }

    public override void WriteCodeElement(CodeEnum codeElement, LanguageWriter writer)
    {
        ArgumentNullException.ThrowIfNull(codeElement);
        ArgumentNullException.ThrowIfNull(writer);

        // Auto-generation header
        writer.WriteLine(AutoGenerationHeader);

        // Namespace
        if (codeElement.Parent is CodeNamespace parentNs && !string.IsNullOrEmpty(parentNs.Name))
        {
            writer.WriteLine($"namespace {parentNs.Name};");
            writer.WriteLine();
        }

        // Documentation
        if (codeElement.Documentation?.DescriptionAvailable == true)
        {
            var description = codeElement.Documentation.GetDescription(static t => t.Name);
            if (!string.IsNullOrEmpty(description))
            {
                writer.WriteLine("/// <summary>");
                writer.WriteLine($"/// {description}");
                writer.WriteLine("/// </summary>");
            }
        }

        // Object ID
        codeElement.CustomData.TryGetValue("object-id", out var objectId);
        objectId ??= "0";

        // Access modifier
        var accessModifier = codeElement.Access == AccessModifier.Public ? string.Empty : "internal ";

        // Enum name
        var enumName = codeElement.Name;

        // Pragma disable for object
        codeElement.CustomData.TryGetValue("pragmas", out var pragmas);
        if (!string.IsNullOrEmpty(pragmas))
            writer.WriteLine($"#pragma warning disable {pragmas}");

        writer.WriteLine($"{accessModifier}enum {objectId} \"{enumName}\"");

        if (!string.IsNullOrEmpty(pragmas))
            writer.WriteLine($"#pragma warning restore {pragmas}");

        writer.StartBlock();

        // Object properties (e.g., Extensible = true)
        var objectProps = codeElement.Options
            .Where(o => o.CustomData.ContainsKey("object-property"))
            .ToList();

        if (objectProps.Count == 0)
        {
            // Default: add Extensible = true
            writer.WriteLine("Extensible = true;");
        }
        else
        {
            foreach (var prop in objectProps)
            {
                var propValue = prop.CustomData.TryGetValue("value", out var val) ? val : "true";
                writer.WriteLine($"{prop.Name} = {propValue};");
            }
        }

        writer.WriteLine();

        // Enum values
        var valueOptions = codeElement.Options
            .Where(o => !o.CustomData.ContainsKey("object-property"))
            .ToList();

        for (var i = 0; i < valueOptions.Count; i++)
        {
            var option = valueOptions[i];
            var optionName = option.Name.ToFirstCharacterUpperCase();
            var wireName = option.WireName;

            writer.WriteLine($"value({i.ToString(CultureInfo.InvariantCulture)}; \"{optionName}\")");
            writer.StartBlock();
            writer.WriteLine($"Caption = '{wireName}', Locked = true;");
            writer.CloseBlock();
        }
    }
}
